<?php

/*
 * Uses wp_maill plugin for sending emails through given SMTP
 */

class BMailer
{
	private $_username;
	private $_password;
	private $_email;
	private $_msg_subject;
	private $_msg_body;	
	private $_err;
	
	
	public function __construct($username, $password, $email)
	{
		$this -> _err = new WP_Error();
		$this -> _err -> add("send_mail", "Sending mail failed.");
		$this -> _username = $username;
		$this -> _password = $password;
		$this -> _email = $email;
	}
	
	public function send_mail()
	{
		 add_filter('wp_mail_content_type',create_function('', 'return "text/html"; '));
		 $headers = "From: <ecp_admin>" . "\r\n\\";
		 if(!wp_mail($this -> _email, $this -> _msg_subject, $this -> _msg_body, $headers))
		 {
		 	return $this -> _err -> get_error_message("send_mail");
		 }
	}
	
	public function add_content($subject, $body)
	{
		$this -> _msg_subject = $subject;
		$this -> _msg_body = $body;
		$this -> _prepare_mail();
	}
	
	private function _prepare_mail()
	{
		if(empty($this -> _msg_subject))
		{
			$this -> _msg_subject = "ECP Registration Info";
		}
		else
		{
			$this -> _msg_subject = $this -> _templateFormater($this -> _msg_subject);
		}
		
		if(empty($this -> _msg_body))
		{
			$this -> _msg_body = "THIS IS AUTOGENERATED MESSAGE. DO NOT REPLY. \n
						 You have been registered as student on <a href='edgeincollegeprep.com'>ECP website</a>. You can log-in using this credentials: \n
						 		username : {$this -> _username} \n
						 		password : {$this -> _password} \n
						 Thank you for registering.";
		}
		else
		{
			$header_msg_body = "THIS IS AUTOGENERATED MESSAGE. DO NOT REPLY. \n";
			$this -> _msg_body = $header_msg_body.$this -> _templateFormater($this -> _msg_body);
		}
	}
	
	private function _templateFormater($template_string)
	{
		$template_msg = str_replace("{user}", $this -> _user ,$template_string);
		$template_msg = str_replace("{username}", $this -> _username, $template_msg);
		$template_msg = str_replace("{password}", $this -> _password, $template_msg);
		return $template_msg;
	}
}

?>