/*
 * Transposh v0.7.6
 * http://transposh.org/
 *
 * Copyright 2011, Team Transposh
 * Licensed under the GPL Version 2 or higher.
 * http://transposh.org/license
 *
 * Date: Tue, 02 Aug 2011 03:11:42 +0300
 */
(function(a){function f(a){var b;return typeof t_jp.l==="object"&&(b=t_jp.l[a])?b:a}function p(c,e,d){a.trim(e).length===0&&(e=a("[data-token='"+c+"']").attr("data-orig"));var f=function(){var c=a(this).attr("id").substr(a(this).attr("id").lastIndexOf("_")+1),e=a(b+"img_"+c);a(b+c).attr("data-source",d);e.removeClass("tr-icon-yellow").removeClass("tr-icon-green");d==0?e.addClass("tr-icon-green"):d&&e.addClass("tr-icon-yellow")};a("*[data-token='"+c+"'][data-hidden!='y']").html(e).each(f);a("*[data-token='"+
c+"'][data-hidden='y']").attr("data-trans",e).each(f);a(b+"translation").data("origval",e);a(b+"translation").keyup()}function m(b,e){p(b,e,0);a.ajax({type:"POST",url:t_jp.post_url,data:{ln0:t_jp.lang,sr0:0,translation_posted:"2",items:1,tk0:b,tr0:e},error:function(a){alert("Error !!! failed to translate.\n\nServer's message: "+a.statusText)}})}function u(b,e){a.ajax({url:"http://ajax.googleapis.com/ajax/services/language/translate?v=1.0&q="+encodeURIComponent(b)+"&langpair=%7C"+t_jp.lang,dataType:"jsonp",
success:e})}function v(){u(a(b+"original").val(),function(c){c.responseStatus===200&&a(b+"translation").val(a("<div>"+a.trim(c.responseData.translatedText)+"</div>").text()).keyup()})}function w(b,e){a.ajax({url:"http://api.microsofttranslator.com/V2/Ajax.svc/Translate?appId="+t_jp.MSN_APPID+"&to="+t_jp.binglang+"&text="+encodeURIComponent(b),dataType:"jsonp",jsonp:"oncomplete",success:e})}function x(){w(a(b+"original").val(),function(c){a(b+"translation").val(a("<div>"+a.trim(c)+"</div>").text()).keyup()})}
function y(b,e){a.ajax({url:"http://api.apertium.org/json/translate?q="+encodeURIComponent(b)+"&langpair=en%7C"+t_jp.lang,dataType:"jsonp",success:e})}function z(){y(a(b+"original").val(),function(c){a(b+"translation").val(a("<div>"+a.trim(c.responseData.translatedText)+"</div>").text()).keyup()})}function n(b){var e,d,f;e=a(b).dialog("widget").find(".ui-dialog-title");d=e.css("margin-right");f=e.css("margin-left");e.css({"float":i,"margin-right":f,"margin-left":d});b=a(b).dialog("widget").find(".ui-dialog-titlebar-close");
d=b.css("right");f=b.css("left");b.css({right:f,left:d})}function A(){var c=b+"confirmdialog";a(c).remove();a('<div id="'+d+'confirmdialog" title="'+f("Close without saving?")+'"><span class="ui-icon ui-icon-alert" style="float:'+i+"; margin-bottom:20px; margin-"+j+':7px"></span><span style="clear:both">'+f("You have made a change to the translation. Are you sure you want to discard it?")+'<span><span id="'+d+'dcbar" style="display:block"><button id="'+d+'cancel">'+f("Cancel")+'</button><button id="'+
d+'discard">'+f("Discard")+"</button></span>NaN").appendTo("body").dialog({resizable:!1,modal:!0,minHeight:50,overlay:{backgroundColor:"#000",opacity:0.5}});a(b+"cancel").button({icons:{primary:"ui-icon-closethick"},text:!1}).click(function(){a(c).dialog("close")});a(b+"discard").button({icons:{primary:"ui-icon-check"},text:!1}).click(function(){a(b+"translation").data("changed",!1);a(c).dialog("close");a(b+"dialog").dialog("close")});a(b+"dcbar").css({"float":j}).buttonset();a("html").attr("dir")===
"rtl"&&(n(c),a(b+"dcbar button:first").addClass("ui-corner-"+i).removeClass("ui-corner-"+j),a(b+"dcbar button:last").addClass("ui-corner-"+j).removeClass("ui-corner-"+i))}function B(c){var e=b+"historydialog";a(e).remove();a('<div id="'+d+'historydialog" title="'+f("History")+'">'+f("Loading...")+"</div>").appendTo("body");a(e).css("padding",0).dialog({width:"450px",show:"slide"});a("html").attr("dir")==="rtl"&&n(e);a.ajax({url:t_jp.post_url,data:{tr_token_hist:a(b+c).attr("data-token"),lang:t_jp.lang},
dataType:"json",cache:!1,success:function(l){var h,g,q,r;a(e).empty().append('<table width="100%"><col style="width: 80%;"><col><col><thead><tr> <th>'+f("Translated")+"</th><th>"+f("By")+"</th><th>"+f("At")+"</th></tr></thead><tbody></tbody></table>");a.each(l,function(b,c){switch(c.source){case "1":h="tr-icon-google";g=f("google");break;case "2":h="tr-icon-bing";g=f("bing");break;case "3":h="tr-icon-apertium";g=f("apertium");break;default:h="ui-icon-person",g=f("manual translation")}if(c.user_login===
null)c.user_login=c.translated_by;q='<span class="ui-button ui-widget ui-button-icon-only" style="width: 18px; border: 0px; margin-'+j+': 3px"><span title="'+g+'" style="cursor: default" class="ui-button-icon-primary ui-icon '+h+'"></span><span class="ui-button-text" style="display: inline-block; "></span></span>';r=c.can_delete?'<span class="'+d+'delete" title="'+f("delete")+'" style="width: 18px; margin-'+i+': 3px">':"";a(e+" tbody").append("<tr><td>"+c.translated+'</td><td id="'+d+'histby">'+q+
c.user_login+'</td><td id="'+d+'histstamp">'+c.timestamp+r+"</td></tr>")});a(b+"histby,"+b+"histstamp").css("white-space","nowrap");a(e+" th").addClass("ui-widget-header").css("padding","3px");a(e+" td").addClass("ui-widget-content").css("padding","3px");a("."+d+"delete").button({icons:{primary:"ui-icon-circle-close"},text:!1}).click(function(){var d=a(this).parents("tr");a.ajax({url:t_jp.post_url,data:{tr_token_hist:a(b+c).attr("data-token"),timestamp:a(this).parents("tr").children(":last").text(),
action:"delete",lang:t_jp.lang},dataType:"json",cache:!1,success:function(e){e===!1?a(d).children().addClass("ui-state-error"):(a(d).empty(),p(a(b+c).attr("data-token"),e.translated,e.source))}})});a("."+d+"delete .ui-button-text").css("display","inline-block")}})}function o(c){a(b+"original").val(a(b+c).attr("data-orig"));a(b+"translation").val(a(b+c).html());a(b+c).attr("data-trans")&&a(b+"translation").val(a(b+c).attr("data-trans"));a(b+"translation").data("origval",a(b+"translation").val());a(b+
"approve").button("enable");a(b+"prev").button("enable");a(b+"next").button("enable");a(b+(Number(c)-1)).length||a(b+"prev").button("disable");a(b+(Number(c)+1)).length||a(b+"next").button("disable");c=a(b+c).attr("data-srclang");if(c===void 0)c=t_jp.olang;a(b+"orglang").text(l[c]);a(b+"historydialog").remove();a(b+"translation").keyup()}function k(c){var e="",k="",h="",g=b+"dialog";t_jp.msn&&(e='<button class="'+d+'suggest" id="'+d+'bing">'+f("bing suggest")+"</button>");t_jp.google&&(k='<button class="'+
d+'suggest" id="'+d+'google">'+f("google suggest")+"</button>");t_jp.apertium&&(h='<button class="'+d+'suggest" id="'+d+'apertium">'+f("apertium suggest")+"</button>");a(g).remove();a('<div id="'+d+'dialog" title="'+f("Edit Translation")+'"/>').appendTo("body");a(g).css("padding","1px").append('<div style="width: 100%"><label for="original">'+f("Original text")+' (<a href="#" title="'+f("read alternate translations")+'" id="'+d+'orglang"></a>)</label><textarea cols="80" row="3" name="original" id="'+
d+'original" readonly="y"/><span id="'+d+'utlbar"><button id="'+d+'prev">'+f("previous translation")+'</button><button id="'+d+'zoom">'+f("find on page")+'</button><button id="'+d+'next">'+f("next translation")+'</button></span><label for="translation">'+f("Translate to")+'</label><textarea cols="80" row="3" name="translation" lang="'+t_jp.lang+'"id="'+d+'translation"/><span id="'+d+'ltlbar"><button id="'+d+'history">'+f("view translation log")+'</button><button id="'+d+'keyboard">'+f("virtual keyboard")+
"</button>"+k+e+h+'<button id="'+d+'approve">'+f("approve translation")+"</button></span></div>");a(b+"utlbar,"+b+"ltlbar").css({"float":j}).buttonset();a(g+" textarea").css({width:"483px",padding:".4em",margin:"2px 0 0 0",resize:"vertical"}).addClass("text ui-widget-content ui-corner-all");a(g+" label").css({display:"block",clear:"both"});a(b+"orglang").click(function(){a(b+"langmenu").length?a(b+"langmenu").toggle():a.xLazyLoader({js:[t_jp.plugin_url+"/js/jquery.ui.menu.js"],success:function(){a.ajax({url:t_jp.post_url,
data:{tr_token_alt:a(b+c).attr("data-token")},dataType:"json",cache:!1,success:function(e){var f;if(!(f=a(b+c).attr("data-srclang")))f=t_jp.olang;var h='<li data-translated="'+a(b+c).attr("data-orig")+'"><a href="#">'+l[f]+"</a></li>";a(e).each(function(a,b){b.lang!==t_jp.lang&&(h=h+'<li data-translated="'+b.translated+'"><a href="#">'+l[b.lang]+"</a></li>")});a('<ul style="position: absolute; top: 0px" id="'+d+'langmenu">'+h).appendTo(g);a(b+"langmenu").menu({select:function(c,d){a(this).hide();
a(b+"original").val(d.item.attr("data-translated"));a(b+"orglang").text(d.item.text()).addClass("ui-state-highlight");l[f]===d.item.text()&&a(b+"orglang").removeClass("ui-state-highlight")},input:a(this)}).show().css({top:0,left:0}).position({my:i+" top",at:i+" bottom",of:a(b+"orglang")})}})}});return!1});a(b+"prev").button({icons:{primary:"ui-icon-seek-"+s},text:!1});a(b+"zoom").button({icons:{primary:"ui-icon-search"},text:!1});a(b+"next").button({icons:{primary:"ui-icon-seek-"+t},text:!1});a(b+
"prev").click(function(){if(a(b+"translation").data("changed")){var d=a(b+"translation").val(),e=a(b+c).attr("data-token");m(e,d)}c=Number(c)-1;o(c)});a(b+"next").click(function(){if(a(b+"translation").data("changed")){var d=a(b+"translation").val(),e=a(b+c).attr("data-token");m(e,d)}c=Number(c)+1;o(c)});a(b+"zoom").click(function(){a("html, body").animate({scrollTop:a(b+c).offset().top},500);a(g).dialog("widget").css({top:a(g).dialog("widget").offset().top-window.scrollY,position:"fixed"});a(b+c).animate({opacity:0.1},
"slow",function(){a(g).dialog("widget").css({top:a(g).dialog("widget").offset().top,position:"absolute"})}).animate({opacity:1},"slow").animate({opacity:0.1},"slow").animate({opacity:1},"slow").animate({opacity:0.1},"slow").animate({opacity:1},"slow")});a(b+"history").button({icons:{primary:"ui-icon-clipboard"},text:!1}).click(function(){B(c)});a(b+"keyboard").button({icons:{primary:"ui-icon-calculator"},text:!1}).click(function(){a.xLazyLoader({js:[t_jp.plugin_url+"/js/keyboard.js"],css:[t_jp.plugin_url+
"/css/keyboard.css"],success:function(){VKI_attach(a(b+"translation").get(0));VKI_show(a(b+"translation").get(0))}})});a(b+"google").button({icons:{primary:"tr-icon-google"},text:!1}).click(function(){v();a("."+d+"suggest").button("enable");a(this).button("disable")});a(b+"bing").button({icons:{primary:"tr-icon-bing"},text:!1}).click(function(){x();a("."+d+"suggest").button("enable");a(this).button("disable")});a(b+"apertium").button({icons:{primary:"tr-icon-apertium"},text:!1}).click(function(){z();
a("."+d+"suggest").button("enable");a(this).button("disable")});a(b+"approve").button({icons:{primary:"ui-icon-check"},text:!1}).click(function(){var d=a(b+"translation").val(),e=a(b+c).attr("data-token");(a(b+"translation").data("changed")||a(b+c).attr("data-source")!=="0")&&m(e,d)});a(b+"translation").keyup(function(){a(this).data("origval")!==a(this).val()?(a(this).addClass("ui-state-highlight"),a(b+"approve").button("enable"),a(this).data("changed",!0)):(a(this).removeClass("ui-state-highlight"),
a(b+c).attr("data-source")==="0"&&a(b+"approve").button("disable"),a(this).data("changed",!1))});o(c);a(g).dialog({resizable:!1,width:500});a("html").attr("dir")==="rtl"&&n(g);a(b+"orglang").blur();a(g).bind("dialogclose",function(){typeof VKI_close==="function"&&VKI_close(a(b+"translation").get(0));a(b+"historydialog").remove()});a(g).bind("dialogbeforeclose",function(){return a(b+"translation").data("changed")?(A(),!1):!0})}var l={en:"English",af:"Afrikaans",sq:"Shqip",ar:"\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
hy:"\u0540\u0561\u0575\u0565\u0580\u0565\u0576",az:"az\u0259rbaycan dili",eu:"Euskara",be:"\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f",bg:"\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438",ca:"Catal\u00e0",zh:"\u4e2d\u6587 - \u7b80\u4f53","zh-tw":"\u4e2d\u6587 - \u6f22\u5b57",hr:"Hrvatski",cs:"\u010ce\u0161tina",da:"Dansk",nl:"Nederlands",eo:"Esperanto",et:"Eesti keel",fi:"Suomi",fr:"Fran\u00e7ais",gl:"Galego",ka:"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8",de:"Deutsch",el:"\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac",
ht:"Krey\u00f2l ayisyen",he:"\u05e2\u05d1\u05e8\u05d9\u05ea",hi:"\u0939\u093f\u0928\u094d\u0926\u0940; \u0939\u093f\u0902\u0926\u0940",hu:"Magyar",is:"\u00cdslenska",id:"Bahasa Indonesia",ga:"Gaeilge",it:"Italiano",ja:"\u65e5\u672c\u8a9e",ko:"\uc6b0\ub9ac\ub9d0",la:"lat\u012bna",lv:"Latvie\u0161u valoda",lt:"Lietuvi\u0173 kalba",mk:"\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a",ms:"Bahasa Melayu",mt:"Malti",no:"Norsk",fa:"\u0641\u0627\u0631\u0633\u06cc",
pl:"Polski",pt:"Portugu\u00eas",ro:"Rom\u00e2n\u0103",ru:"\u0420\u0443\u0441\u0441\u043a\u0438\u0439",sr:"C\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a",sk:"Sloven\u010dina",sl:"Sloven\u0161\u010dina",es:"Espa\u00f1ol",sw:"Kiswahili",sv:"svenska",tl:"Tagalog",th:"\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22",tr:"T\u00fcrk\u00e7e",uk:"\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430",ur:"\u0627\u0631\u062f\u0648",vi:"Ti\u1ebfng Vi\u1ec7t",cy:"Cymraeg",yi:"\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9"},
d=t_jp.prefix,b="#"+d,s="prev",t="next",j="right",i="left";a("html").attr("dir")==="rtl"&&(j="left",i="right",s="next",t="prev");a("."+d).each(function(){var c=a(this).attr("id").substr(a(this).attr("id").lastIndexOf("_")+1),e;a(this).after('<span id="'+d+"img_"+c+'" class="tr-icon" title="'+a(this).attr("data-orig")+'"></span>');e=a(b+"img_"+c);e.click(function(){typeof a.fn.tabs!=="function"||typeof a.fn.buttonset!=="function"||typeof a.fn.dialog!=="function"?(a.ajaxSetup({cache:!0}),a.getScript(t_jp.plugin_url+
"/js/lazy.js",function(){a.xLazyLoader({js:t_jp.jQueryUI+"jquery-ui.min.js",css:t_jp.jQueryUI+"themes/"+t_jp.theme+"/jquery-ui.css",success:function(){t_jp.locale?a.xLazyLoader({js:[t_jp.plugin_url+"/js/l/"+t_jp.lang+".js"],success:function(){k(c)}}):k(c)}})})):t_jp.locale?a.xLazyLoader({js:[t_jp.plugin_url+"/js/l/"+t_jp.lang+".js"],success:function(){k(c)}}):k(c);return!1}).css({border:"0px",margin:"1px",padding:"0px"});a(this).attr("data-source")==="0"?e.addClass("tr-icon-green"):a(this).attr("data-source")&&
e.addClass("tr-icon-yellow");a(this).attr("data-hidden")==="y"&&e.css({opacity:"0.6"})})})(jQuery);
